Mvc_HireMeNow/Mvc_HireMeNow/Controllers/JobProviderController.cs
using AutoMapper;
using Mvc_HireMeNow.Interfaces;
using Microsoft.AspNetCore.Mvc;
using Mvc_HireMeNow.Dtos;
using Mvc_HireMeNow.Interfaces;
using Mvc_HireMeNow.Models;
using System.Threading.Tasks.Dataflow;
using Microsoft.CodeAnalysis.Elfie.Diagnostics;
using Mvc_HireMeNow.Services;
using System.ComponentModel.Design;

namespace Mvc_HireMeNow.Controllers
{
	public class JobProviderController : Controller
	{
		IMapper _mapper;
		IJobRepository _jobRepository;
		IUserRepository _userRepository;
		IApplicationRepository _applicationRepository;
		IInterviewServices _interviewServices;
		public JobProviderController(IMapper mapper, IJobRepository jobRepository,IUserRepository userRepository,IApplicationRepository applicationRepository,IInterviewServices interviewServices)
		{
			_mapper = mapper;
			_jobRepository = jobRepository;
			_userRepository = userRepository;
			_applicationRepository = applicationRepository;
			_interviewServices = interviewServices;
		

        }

		public IActionResult Index()
		{
			return View();
		}
		public ActionResult PostJob()
		{
			return View();
		}
		[HttpPost]
		[ValidateAntiForgeryToken]
		public IActionResult PostJob(JobDto jobDto)
		{
			var uid = HttpContext.Session.GetString("UserId");


			
			User user = _userRepository.getById(new Guid(uid));
			jobDto.CompanyId = (Guid)user.CompanyId;
			var job = _mapper.Map<Job>(jobDto);
			bool result=_jobRepository.Create(job);
		
			
				TempData["Message"] = "Successfully posted Job";
			return View();


		}
		[HttpGet]
		public IActionResult ListApplication()
		{
			var uid = HttpContext.Session.GetString("UserId");
			var user = _userRepository.getById(new Guid(uid));
			TempData["CompanyID"] = user.CompanyId;
			var cmpid = user.CompanyId;
			List<Application> applications = _applicationRepository.GetAllApplication((Guid)cmpid);


			


			
			return View(applications);


		}
		[HttpGet]
		public IActionResult InterviewShedule(Guid parameter)
        {
           Application Applications = _applicationRepository.GetApplication(parameter);
			//Applications.ForEach((e) =>
			//{
			//    e.Job = _jobRepository.GetJobById(e.JobId.Value);

			//});

			//var  users = _userRepository.getById(parameter);
			InterviewDto interviewDto = new();
			interviewDto.JobId = (Guid)(Applications?.Job?.Id.Value);
			
			ViewBag.jobTitle = Applications.Job.Title;
		
			ViewBag.ComapanyId = Applications.CompanyId;
			interviewDto.JobseekerId = Applications.User.Id;
			
			interviewDto.CompanyId = (Guid)Applications.CompanyId;

			return View(interviewDto);

        }
		[HttpPost]
		public IActionResult InterviewShedule(InterviewDto interviewDto,Guid CompanyId,Guid JobseekerId,Guid JobId)
		{
			interviewDto.JobId = JobId;
			interviewDto.CompanyId = CompanyId;
			interviewDto.JobseekerId = JobseekerId;
			
			var interview = _mapper.Map<Interview>(interviewDto);
            _interviewServices.sheduleinterview(interview);
			TempData["Message"] = "Success Fully Added";
			return View(interviewDto);
        }

		[HttpGet]
		public IActionResult ListJobs()
		{
			return View();
		}
		[HttpGet]
		public IActionResult SheduledInterviewList()
		{
			var cmpId = HttpContext.Session.GetString("CompanyId");
			List<Interview> sheduledinterviews = _interviewServices.sheduledInterviewList(new Guid(cmpId));
			if(sheduledinterviews!=null)
			{
				

				return View(sheduledinterviews);
			}
			else
			{
				return BadRequest("no interviews sheduled");
			}
			
		}
		
	}
}

Mvc_HireMeNow/Mvc_HireMeNow/Views/JobProvider/InterviewShedule.cshtml
@model Mvc_HireMeNow.Dtos.InterviewDto

@{
	ViewData["Title"] = "InterviewShedule";
	Layout = "~/Views/Shared/_JobProviderLayout.cshtml";
}



<div class="container-fluid">
	<div class="row">
		
		<div class="col-md-10">
			<div class="row">
				<div class="col-md-11 mt-5  border-bottom pb-4 ">
					<!-- <img class="img-fluid float-right m-2 pt-4" src="~/asset/images/arrow-down.png"> -->
					<!-- <span class="float-right pt-3 m-2"><strong>Olivia</strong></span> -->
					<select class="form-select border-0 float-right  mt-4" style="float:right;width: 100px;" aria-label="Default select example">
						<option selected><strong>Olivia</strong></option>

					</select>
					<img class="img-fluid float-right" style="float:right" src="~/publicassets/JobProvider/InterviewShedule/images/cheerful-curly-business-girl-wearing-glasses 2.png">
					<img class="img-fluid float-right pt-2 m-2 " style="float:right" src="~/publicassets/JobProvider/InterviewShedule/images/Group 5689.png" width="30" height="30">
				</div>
			</div>
			<div class="row">
				<div class="col-md-11 shadow-sm">
					<div class="row">
						<div class="col-md-11" style="float:left;">
							<h3 class="h3-default text-right mr-5 " style="float:right;">Short List</h3>
						</div>
					</div>
					<div class="row">
						<div class="col-md-10 mx-auto d-block border-top ">
							<form method="post">
								<div class="form-group text-dark">
									<label for="Job Title"><h4>Job Title</h4></label>
									<input type="text" asp-for="JobId" name="Post" placeholder="Select Jobtitle" class="form-control bg-light p-4 border-0 rounded " required="" value="@ViewBag.jobTitle">
								</div>
								<div class="form-group text-dark p-1">
									<label for="Date"><h4>Date</h4></label>
									<img class="img-fluid float-right" style="float:right" src="~/publicassets/JobProvider/InterviewShedule/images/calendar (4) 1.png">
									<input asp-for="Date" type="date" id="datepicker" name="date" placeholder="Select Date" class="form-control bg-light p-4 border-0 rounded w-75 " required="">
								</div>
								<div class="form-group text-dark p-1">
									<label for="Time"><h4>Time</h4></label>
									<img class="img-fluid float-right" style="float:right" src="~/publicassets/JobProvider/InterviewShedule/images/clock 1.png">
									<input asp-for="Time" type="time" name="time" placeholder=" Enter time" class="form-control bg-light p-4 border-0 rounded w-75" required="">
								</div>
								<div class="form-group text-dark p-2">
									<label for="Location"><h4>Location</h4></label>
									<img class="img-fluid float-right" style="float:right" src="~/publicassets/JobProvider/InterviewShedule/images/location 1.png">
									<input asp-for="Location" type="text" name="location" placeholder="Enter location" class="form-control bg-light p-4 border-0 rounded mb-5 w-75" required="">
								</div>
								<input type="hidden" name="JobseekerId" value="@Model.JobseekerId" />
								<input type="hidden" name="CompanyId" value="@Model.CompanyId" />
								<input type="hidden" name="JobId" value="@Model.JobId" />
								@if(@TempData["Message"]!=null)
								{
									<p> @TempData["Message"] </p>
								}
							
								<div class="form-group d-inline ">
									<input class="btn  text-white mr-5 bg-primary text-white" type="submit" value="Send"></input>
									<label><h5>Push Notification</h5></label>
									<img class="img-fluid mr-5" src="~/publicassets/JobProvider/InterviewShedule/images/Group 14.png">
									<label><h5>Email Notifications</h5></label>
									<img class="img-fluid" src="~/publicassets/JobProvider/InterviewShedule/images/Group 14.png">
								</div>
							</form>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>


@section Scripts {
	@{
		await Html.RenderPartialAsync("_ValidationScriptsPartial");
	}
}

Mvc_HireMeNow/Mvc_HireMeNow/Views/JobProvider/ListApplication.cshtml
@model IEnumerable<Mvc_HireMeNow.Models.Application>

@{
    ViewData["Title"] = "ListApplication";
    Layout = "~/Views/Shared/_JobProviderLayout.cshtml";
}

<link href="~/publicassets/css/home.css" rel="stylesheet" />
<style>
    .jobData{
        /*width: 80%;*/
    }

    .btn-apply {
        width: -webkit-fill-available;
        height: 40px;
    }

    .job-card {
        /*width: 60%;*/
        margin:  auto;
        margin-bottom: 13px;
        padding: 10px;
        box-shadow: 3px 4px 17px 0px #504d4d7d;
    }

       /* .job-card :hover {
       
        box-shadow: 3px 4px 17px 0px #504d4d7d;
    }*/
    .applySection{
        display: flex;
        align-content: center;
        flex-direction: column;
        justify-content: center;
    }

    .logoDiv{
        display: flex;
        align-content: center;
        flex-direction: column;
        justify-content: center;
        align-items: center;
    }

    .jobListDiv{
        justify-content: center;
    }

    progress {
        width: 100%;
        height: 8px;
        background-color: #ddd;
        border: none;
        border-radius: 5px;
        margin-top:5px;
    }

        progress::-webkit-progress-bar {
            background-color: #ddd;
            border-radius: 5px;
        }

        progress::-webkit-progress-value {
            background-color: #4CAF50;
            border-radius: 5px;
        }

    .JobWrapper {
        display: flex;
        flex-direction: row;
        flex-wrap: wrap;
        align-content: center;
        justify-content: center;
        align-items: center;
    }

    .tags{
        flex-wrap: wrap
    }

    .progressSpan{
        font-size: small;
    }
   
</style>
<div>
    <h1 align="center">
        <font size="6" face="system-ui" color="black" align="center">
            <b>Find your </b>
        </font>
        <font size="6" face="system-ui" color="#20a6fc" align="center">
            <b>dream job </b>
        </font>
    </h1>
    <p align="center">
        <font face="arial">Find your next career at companies like HubSpot, Nike, and Dropbox</font>
    </p>
    <h2 align="center" color="#3487bf">All Applications</h2>
    <div class="row jobListDiv" >

        <div class="left col-md-8 ">
            @foreach (var app in Model)
            {
                <div class="job-card" style="">
                <div width="" class="JobWrapper">
                        <div align="center" class="col-md-2 logoDiv">
                          
                            <img src="~/publicassets/images/google symbol.png" width="50px" alt="Google" title="Google" height="50px">
                    </div>
                    <div class="col-md-8 jobData">
                        <b >
                            <font size="5px" color="#3487bf">@app.Job.Title </font>
                        </b>
                        <br>
                       
                        <div>
                          company: <b>@app.Job.Company.Name</b> <br>
                           Location: <b>@app.Job.Location</b> <br>
                        

                        </div>
                        <br>
                        <div class="">

                            <div class="row tags">
                                <div class="fulltime"> Full Time </div>
                                <div class="marketing"> <b>Marketing</b> </div>
                                <div class="design"> Designing </div>
                            </div>  

                        </div>
                        <br>

                    </div>
              @*      <div class="col-md-2 applySection">
                            <form method="post">
                               
                                @{
                                    if (TempData["UserId"] == null)
                                    {
                                        TempData["Id"] = job.Id;
                                       
                                        <input type="hidden" name="parameter" value="@job.Id" />
                                        <input type="submit" class="btn btn-outline-primary btn-apply" value="Apply" asp-page-handler="ButtonClick" >
                                    }
                                    else{
                                        
                                        <input type="hidden" name="parameter" value="@job.Id" />
                                        <input type="submit" class="btn btn-outline-primary btn-apply" value="Apply" asp-page-handler="ButtonClick" >
                                    }

                            }
                        </form>
                      

                            <progress id="progressBar" value=@job.AppliedCount max=@job.VacanciesCount></progress>
                            <span class="progressSpan">@job.AppliedCount applied of @job.VacanciesCount capacity</span>
                    </div>*@
                 <div class="col-md-2 applySection">
                            @using (Html.BeginForm("InterviewShedule", "JobProvider", FormMethod.Get))
                               
                               
                                    if (TempData["CompanyId"] == null)
                                    {
                                        TempData["Id"] = app.Id;
                                       
                                        <input type="hidden" name="parameter" value="@app.Id" />
                                        <input  type="submit" class="btn btn-outline-primary btn-apply" value="Shedule" asp-page-handler="ButtonClick">
                                    }
                                    else{
                                        
                                        <input type="hidden" name="parameter" value="@app.Id" />
                                        <input type="submit" class="btn btn-outline-primary btn-apply" value="Shedule"  >
                                                    //<a asp-page="InterviewShedule"  class="btn btn-outline-primary btn-apply" asp-route-id="@app.Id">Schedule Interview</a>
        

                                    }

                            
                    
                      
                </div>

                    </div>
                </div>
               
            }
           
           
            
        </div>
        </div>

Mvc_HireMeNow/Mvc_HireMeNow/Views/JobProvider/PostJob.cshtml
 @model Mvc_HireMeNow.Dtos.JobDto;
@{
	Layout = "_JobProviderLayout";
}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</head>
<body>
	<div class="container-fluid">
		<div  class="row">
			<div class="col-md-2 text-nowrap bg-primary">
				<nav class="navbar  navbar-expand-md sidebar navbar-dark">
					<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
	  					<span class="navbar-toggler-icon bg-dark"></span>
	  				</button>
	 				<div class="collapse  navbar-collapse sidebar " id="collapsibleNavbar">
	 					<ul class="list-group text-white list-unstyled">
	 						<li class="list-group-item border-0 bg-primary pt-5 pb-5 ">
	 							<h4 class="h4-fluid">HireMe Now</h4>
	 						</li>
	 						
	 						<li class="list-group-item border-0 bg-primary">
								<p><img src="/publicassets/JobProvider/PostJob/images/dashboard 1 (2).png">  Dash Board</p>
	 						</li>
	 						<li class="list-group-item border-0 bg-primary">
								<p><img src="/publicassets/JobProvider/PostJob/images/suitcase 2 (1).png">  Jobs</p>
	 						</li>
			    			<li class="list-group-item border-0 bg-primary">
								<p><img src="/publicassets/JobProvider/PostJob/images/application (1) 1 (2).png">  Applications</p>
	 						</li>
			   				<li class="list-group-item border-0 bg-primary">
								<p><img src="/publicassets/JobProvider/PostJob/images/question (1) 1 (2).png"> Interviews</p>
	 						</li>
	 						<li class="list-group-item border-0 bg-primary">
								<p><img src="/publicassets/JobProvider/PostJob/images/message 1 (2).png"> Messages</p>
	 						</li>
			    
			    			<li class="list-group-item border-0 bg-primary">
								<p><img src="/publicassets/JobProvider/PostJob/images/settings 1 (1).png">  Settings</p>
	 						</li>
			    			<li class="list-group-item border-0 bg-primary">
								<img class="img-fluid" src="/publicassets/JobProvider/PostJob/images/add-group (1) 1 (2).png"><br>
				        		<span class="text-white">Add New</span>
			    			</li>
	 					</ul>
	 				</div>
 				</nav>
 			</div>
 			<div class="col-md-10">
 				<div class="row">
 					<div class="col-md-12 mt-5 mb-3 border-bottom">
						<img class="img-fluid float-right m-2 pt-4" src="/publicassets/JobProvider/PostJob/images/arrow-down.png">
 						<span class="float-right pt-3 m-2"><strong>Olivia</strong></span>
						<img class="img-fluid float-right" src="/publicassets/JobProvider/PostJob/images/cheerful-curly-business-girl-wearing-glasses 2.png">
						<img class="img-fluid float-right pt-2 m-2 " src="/publicassets/JobProvider/PostJob/images/Group 5689.png" width="30" height="30">
 					</div>
 				</div>
 				<div class="row">
					 <form method="post">
 					<div class="col-md-10 p-5 mx-auto d-block border rounded mb-5" style="border-radius: 30px; box-shadow: 0px 0px 5px 2px gray;">
 						<div class="row">
 							<div class="col-md-10">
 								<div class="form-group">
	 								<label for="jobTitle"><h4>Job Title</h4></label>
	 								<br>
									<input asp-for="Title" class="form-control p-4 bg-light" type="text" name="Title" placeholder="Enter Job Title">
	 							</div>
	 							<div class="form-group">
	 								<label for="description"><h4>Description</h4></label>
	 								<br>
									<input asp-for="Description" class="form-control p-4 bg-light" type="text" name="Description" placeholder="Enter Description">
	 							</div>
	 							<div class="form-group">
	 								<label for="Salary"><h4>Salary</h4></label>
	 								<br>
									<input asp-for="Salary" class="form-control p-4 bg-light" type="text" name="Salary" placeholder="Enter Salary">
	 							</div>
	 							<div class="form-group">
									<label for="Location"><h4>Location</h4></label>
	 								<br>
									<input asp-for="Location" class="form-control p-4 bg-light" type="text" name="Location" placeholder="Enter Location">
	 							</div>
 							</div>
 						</div>
	 					<div class="row pt-4">
	 						<div class="col-md-3">
 								<button class="btn bg-primary pl-5 pr-5"> Post Job</button>
 							</div>
							 @if(TempData["Message"]!=null)
								{
									<p>@TempData["Message"]</p>
									
								}
								<div class="col-md-3">
 								<label >Push Notification</label>
									<img class="img-fluid" src="/publicassets/JobProvider/PostJob/images/Group 14.png">
 							</div>
 							<div class="col-md-3">
 								<label>Email Notification</label>
									<img class="img-fluid" src="/publicassets/JobProvider/PostJob/images/Group 14.png">
							</div>
 						</div>							
 					</div>
					 </form>
 				</div>
 				<div class="row ">
 					<div class="col-md-12 bg-primary ">
						<img class="img-fluid float-left" src="/publicassets/JobProvider/PostJob/images/Decoration (3).png">
						<div class="col-6 position-absolute ">
	 						
							<h2 class="h3-fluid text-white mt-5 font-italic ">Get Your Dream Job......</h2>
							<img class="img-fluid float-right p-5" src="/publicassets/JobProvider/PostJob/images/calendar (2) 2.png">
							<img class="img-fluid  float-right p-5 imgHome " src="/publicassets/JobProvider/PostJob/images/home-button 4.png">
						</div>
 					</div>
				</div>
			</div>
		</div>
	</div>
</body>
</html>

Mvc_HireMeNow/Mvc_HireMeNow/Views/JobProvider/SheduledInterviewList.cshtml
@model IEnumerable<Mvc_HireMeNow.Models.Interview>

@{
	Layout = "~/Views/Shared/_PubLayout.cshtml";

}

<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</head>
<body>
	<div class="container-fluid">
		<div class="row">
			<div class="col-md-2 bg-primary">
				<nav class="navbar  navbar-expand-md sidebar navbar-dark">
					<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
						<span class="navbar-toggler-icon bg-dark"></span>
					</button>
					<div class="collapse  navbar-collapse sidebar " id="collapsibleNavbar">
						<ul class="list-group text-white list-unstyled">
							<li class="list-group-item border-0 bg-primary">
								<div class="w-75 mt-5 pb-2 pt-2 bg-secondary rounded-circle">
									<img class="img-fluid mx-auto d-block" src="~/JobProvider/SheduledInterviewList/images/cheerful-curly-business-girl-wearing-glasses 1.png" width="75" height="75">
								</div>
							</li>
							<li>
								<h4 class="h4-fluid text-center">Olivia<br>olivia@gmail.com</h4>
							</li>
							<li class="list-group-item border-0 bg-primary">
								<p><img src="~/JobProvider/SheduledInterviewList/images/dashboard 1.png">  Dash Board</p>
							</li>
							<li class="list-group-item border-0 bg-primary">
								<p><img src="~/JobProvider/SheduledInterviewList/images/suitcase 2.png">  Jobs</p>
							</li>
							<li class="list-group-item border-0 bg-primary">
								<p><img src="~/JobProvider/SheduledInterviewList/images/application (1) 1.png">  Applications</p>
							</li>
							<li class="list-group-item border-0 bg-primary">
								<p><img src="~/JobProvider/SheduledInterviewList/images/question (1) 1.png"> Interviews</p>
							</li>
							<li class="list-group-item border-0 bg-primary">
								<p><img src="~/JobProvider/SheduledInterviewList/images/message 1.png"> Messages</p>
							</li>

							<li class="list-group-item border-0 bg-primary">
								<p><img src="~/JobProvider/SheduledInterviewList/images/settings 1.png">  Settings</p>
							</li>
							<li class="list-group-item border-0 bg-primary">
								<img class="img-fluid" src="~/JobProvider/SheduledInterviewList/images/add-group (1) 1 (1).png"><br>
								<span class="text-white">Add New</span>
							</li>
						</ul>
					</div>
				</nav>
			</div>
			<div class="col-md-10 bg-light">
				<div class="row bg-white">
					<div class="col-md-10 ">
						<h4 class="h4-fluid mt-3 ">SHORT LIST</h4>

					</div>
					<div class="col-md-2 content-justify-right">
						<img class="img-fluid " src="~/JobProvider/SheduledInterviewList/images/Group 5689.png">
						<img class="img-fluid" src="~/JobProvider/SheduledInterviewList/images/Group 33999.png">
					</div>
				</div>
				<div class="row ">
					<div class="col-md-8 bg-white border rounded-pill  ml-2">
						<div class="input-group ">
							<img class="img-fluid" src="~/JobProvider/SheduledInterviewList/images/search copy 2.png" width="10" height="5">
							<input type="search" class="form-control border-0 " placeholder="Search by Job Title, Interview Date" aria-label="Search" aria-describedby="search-addon">
							<img class="img-fluid" src="~/JobProvider/SheduledInterviewList/images/icon filter.png" width="15" height="10">
						</div>
					</div>
				</div>
				<div class="row">
					<div class="col-md-11 bg-white border rounded mx-auto mt-5 mb-5">
						<div class="row">
							
							<div class="col-md-6   p-5">

								@foreach (var obj in Model)
								{
									<div class="row">
										<div class="col-md-12 pb-3 pt-3 ">
											<img class="img-fluid float-left pb-5" src="~/JobProvider/SheduledInterviewList/images/Company Logo (1).png">
											<h4 class="h4-fluid">@obj.Job.Title</h4>
											<p>
												Date Of Interview : @obj.Date<br>
												Location/Online:@obj.Location<br>
												Time:@obj.Time
											</p>
											<button class="btn bg-primary text-white mx-auto d-block">View</button>
										</div>

									</div>
								}

							</div>
						
							<div class="col-md-6 pb-5 mt-5">
								<img class="img-fluid" src="~/JobProvider/SheduledInterviewList/images/nice-meeting-businessmen 1.png">
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>

		</div>
</body>
</html>